// Built-in protein lookup table.
//
// Ported from the Atomic Nutrition Tracker seed data (USDA-sourced). Only
// protein is carried over - this app tracks protein, not full macros - and
// foods under 2g per serving are dropped because they're noise in a search
// for "what has protein in it".
//
// `protein` is the grams of protein in one `servingSize` `servingUnit` portion.

export interface BuiltInFood {
  name: string;
  servingSize: number;
  servingUnit: string;
  protein: number;
  category: string | null;
}

export const BUILT_IN_FOODS: BuiltInFood[] = [
  { name: 'Coconut Water', servingSize: 240, servingUnit: 'ml', protein: 2, category: 'Beverages' },
  { name: 'Hot Chocolate', servingSize: 240, servingUnit: 'ml', protein: 9, category: 'Beverages' },
  { name: 'Orange Juice', servingSize: 240, servingUnit: 'ml', protein: 2, category: 'Beverages' },
  { name: 'Cheddar Cheese', servingSize: 28, servingUnit: 'g', protein: 7, category: 'Dairy & Alternatives' },
  { name: 'Cream Cheese', servingSize: 28, servingUnit: 'g', protein: 2, category: 'Dairy & Alternatives' },
  { name: 'Feta Cheese', servingSize: 28, servingUnit: 'g', protein: 4, category: 'Dairy & Alternatives' },
  { name: 'Milk (2%)', servingSize: 240, servingUnit: 'ml', protein: 8, category: 'Dairy & Alternatives' },
  { name: 'Milk (skim)', servingSize: 240, servingUnit: 'ml', protein: 8, category: 'Dairy & Alternatives' },
  { name: 'Milk (whole)', servingSize: 240, servingUnit: 'ml', protein: 8, category: 'Dairy & Alternatives' },
  { name: 'Mozzarella Cheese', servingSize: 28, servingUnit: 'g', protein: 6, category: 'Dairy & Alternatives' },
  { name: 'Oat Milk', servingSize: 240, servingUnit: 'ml', protein: 3, category: 'Dairy & Alternatives' },
  { name: 'Parmesan Cheese', servingSize: 28, servingUnit: 'g', protein: 10, category: 'Dairy & Alternatives' },
  { name: 'Soy Milk', servingSize: 240, servingUnit: 'ml', protein: 7, category: 'Dairy & Alternatives' },
  { name: 'BLT Sandwich', servingSize: 1, servingUnit: 'sandwich', protein: 12, category: 'Fast Food & Common Meals' },
  { name: 'Burrito (chicken)', servingSize: 1, servingUnit: 'burrito', protein: 30, category: 'Fast Food & Common Meals' },
  { name: 'Caesar Salad', servingSize: 1, servingUnit: 'serving', protein: 8, category: 'Fast Food & Common Meals' },
  { name: 'Cheeseburger (fast food)', servingSize: 1, servingUnit: 'burger', protein: 22, category: 'Fast Food & Common Meals' },
  { name: 'Chicken Nuggets (6 pc)', servingSize: 6, servingUnit: 'pieces', protein: 14, category: 'Fast Food & Common Meals' },
  { name: 'Grilled Cheese Sandwich', servingSize: 1, servingUnit: 'sandwich', protein: 15, category: 'Fast Food & Common Meals' },
  { name: 'Hamburger (fast food)', servingSize: 1, servingUnit: 'burger', protein: 17, category: 'Fast Food & Common Meals' },
  { name: 'Pizza Slice (cheese)', servingSize: 1, servingUnit: 'slice', protein: 12, category: 'Fast Food & Common Meals' },
  { name: 'Pizza Slice (pepperoni)', servingSize: 1, servingUnit: 'slice', protein: 13, category: 'Fast Food & Common Meals' },
  { name: 'Taco (beef)', servingSize: 1, servingUnit: 'taco', protein: 8, category: 'Fast Food & Common Meals' },
  { name: 'Avocado', servingSize: 100, servingUnit: 'g', protein: 2, category: 'Fruits' },
  { name: 'Bagel (plain)', servingSize: 1, servingUnit: 'medium', protein: 11, category: 'Grains & Carbs' },
  { name: 'Bread (sourdough)', servingSize: 1, servingUnit: 'slice', protein: 4, category: 'Grains & Carbs' },
  { name: 'Bread (white)', servingSize: 1, servingUnit: 'slice', protein: 2.7, category: 'Grains & Carbs' },
  { name: 'Bread (whole wheat)', servingSize: 1, servingUnit: 'slice', protein: 4, category: 'Grains & Carbs' },
  { name: 'Brown Rice (cooked)', servingSize: 100, servingUnit: 'g', protein: 2.3, category: 'Grains & Carbs' },
  { name: 'Cereal (Cheerios)', servingSize: 28, servingUnit: 'g', protein: 3, category: 'Grains & Carbs' },
  { name: 'Cereal (Corn Flakes)', servingSize: 28, servingUnit: 'g', protein: 2, category: 'Grains & Carbs' },
  { name: 'Corn (cooked)', servingSize: 100, servingUnit: 'g', protein: 3.4, category: 'Grains & Carbs' },
  { name: 'Couscous (cooked)', servingSize: 100, servingUnit: 'g', protein: 3.8, category: 'Grains & Carbs' },
  { name: 'English Muffin', servingSize: 1, servingUnit: 'muffin', protein: 5, category: 'Grains & Carbs' },
  { name: 'French Fries', servingSize: 100, servingUnit: 'g', protein: 3.4, category: 'Grains & Carbs' },
  { name: 'Granola', servingSize: 50, servingUnit: 'g', protein: 5, category: 'Grains & Carbs' },
  { name: 'Jasmine Rice (cooked)', servingSize: 100, servingUnit: 'g', protein: 2.4, category: 'Grains & Carbs' },
  { name: 'Oatmeal (cooked)', servingSize: 100, servingUnit: 'g', protein: 2.5, category: 'Grains & Carbs' },
  { name: 'Oats (dry)', servingSize: 40, servingUnit: 'g', protein: 5.3, category: 'Grains & Carbs' },
  { name: 'Pancakes', servingSize: 1, servingUnit: 'medium', protein: 2.4, category: 'Grains & Carbs' },
  { name: 'Pasta (cooked)', servingSize: 100, servingUnit: 'g', protein: 5, category: 'Grains & Carbs' },
  { name: 'Potato (baked)', servingSize: 100, servingUnit: 'g', protein: 2.5, category: 'Grains & Carbs' },
  { name: 'Potato (mashed)', servingSize: 100, servingUnit: 'g', protein: 2, category: 'Grains & Carbs' },
  { name: 'Quinoa (cooked)', servingSize: 100, servingUnit: 'g', protein: 4.4, category: 'Grains & Carbs' },
  { name: 'Spaghetti (cooked)', servingSize: 100, servingUnit: 'g', protein: 5, category: 'Grains & Carbs' },
  { name: 'Sweet Potato (baked)', servingSize: 100, servingUnit: 'g', protein: 2, category: 'Grains & Carbs' },
  { name: 'Tortilla (flour)', servingSize: 1, servingUnit: 'medium', protein: 4, category: 'Grains & Carbs' },
  { name: 'White Rice (cooked)', servingSize: 100, servingUnit: 'g', protein: 2.7, category: 'Grains & Carbs' },
  { name: 'Black Beans (cooked)', servingSize: 100, servingUnit: 'g', protein: 8.9, category: 'Legumes' },
  { name: 'Chickpeas (cooked)', servingSize: 100, servingUnit: 'g', protein: 9, category: 'Legumes' },
  { name: 'Hummus', servingSize: 50, servingUnit: 'g', protein: 2.4, category: 'Legumes' },
  { name: 'Kidney Beans (cooked)', servingSize: 100, servingUnit: 'g', protein: 8.7, category: 'Legumes' },
  { name: 'Lentils (cooked)', servingSize: 100, servingUnit: 'g', protein: 9, category: 'Legumes' },
  { name: 'Navy Beans (cooked)', servingSize: 100, servingUnit: 'g', protein: 8.2, category: 'Legumes' },
  { name: 'Pinto Beans (cooked)', servingSize: 100, servingUnit: 'g', protein: 9, category: 'Legumes' },
  { name: 'Refried Beans', servingSize: 100, servingUnit: 'g', protein: 5.4, category: 'Legumes' },
  { name: 'Soybeans (cooked)', servingSize: 100, servingUnit: 'g', protein: 17, category: 'Legumes' },
  { name: 'Split Peas (cooked)', servingSize: 100, servingUnit: 'g', protein: 8.3, category: 'Legumes' },
  { name: 'Almond Butter', servingSize: 32, servingUnit: 'g', protein: 7, category: 'Nuts & Seeds' },
  { name: 'Almonds', servingSize: 28, servingUnit: 'g', protein: 6, category: 'Nuts & Seeds' },
  { name: 'Cashews', servingSize: 28, servingUnit: 'g', protein: 5, category: 'Nuts & Seeds' },
  { name: 'Chia Seeds', servingSize: 28, servingUnit: 'g', protein: 5, category: 'Nuts & Seeds' },
  { name: 'Flax Seeds', servingSize: 28, servingUnit: 'g', protein: 5, category: 'Nuts & Seeds' },
  { name: 'Hemp Seeds', servingSize: 30, servingUnit: 'g', protein: 10, category: 'Nuts & Seeds' },
  { name: 'Macadamia Nuts', servingSize: 28, servingUnit: 'g', protein: 2.2, category: 'Nuts & Seeds' },
  { name: 'Peanut Butter', servingSize: 32, servingUnit: 'g', protein: 8, category: 'Nuts & Seeds' },
  { name: 'Peanuts', servingSize: 28, servingUnit: 'g', protein: 7, category: 'Nuts & Seeds' },
  { name: 'Pecans', servingSize: 28, servingUnit: 'g', protein: 2.6, category: 'Nuts & Seeds' },
  { name: 'Pistachios', servingSize: 28, servingUnit: 'g', protein: 6, category: 'Nuts & Seeds' },
  { name: 'Pumpkin Seeds', servingSize: 28, servingUnit: 'g', protein: 7, category: 'Nuts & Seeds' },
  { name: 'Sunflower Seeds', servingSize: 28, servingUnit: 'g', protein: 5.5, category: 'Nuts & Seeds' },
  { name: 'Trail Mix', servingSize: 40, servingUnit: 'g', protein: 5, category: 'Nuts & Seeds' },
  { name: 'Walnuts', servingSize: 28, servingUnit: 'g', protein: 4, category: 'Nuts & Seeds' },
  { name: 'Bacon', servingSize: 3, servingUnit: 'slices', protein: 12, category: 'Proteins' },
  { name: 'Beef Steak (ribeye)', servingSize: 100, servingUnit: 'g', protein: 24, category: 'Proteins' },
  { name: 'Beef Steak (sirloin)', servingSize: 100, servingUnit: 'g', protein: 27, category: 'Proteins' },
  { name: 'Chicken Breast (cooked)', servingSize: 100, servingUnit: 'g', protein: 31, category: 'Proteins' },
  { name: 'Chicken Breast (raw)', servingSize: 100, servingUnit: 'g', protein: 22.5, category: 'Proteins' },
  { name: 'Chicken Thigh (cooked)', servingSize: 100, servingUnit: 'g', protein: 26, category: 'Proteins' },
  { name: 'Chicken Wings', servingSize: 100, servingUnit: 'g', protein: 30.5, category: 'Proteins' },
  { name: 'Cod', servingSize: 100, servingUnit: 'g', protein: 18, category: 'Proteins' },
  { name: 'Cottage Cheese (full fat)', servingSize: 100, servingUnit: 'g', protein: 11, category: 'Proteins' },
  { name: 'Cottage Cheese (low fat)', servingSize: 100, servingUnit: 'g', protein: 12, category: 'Proteins' },
  { name: 'Egg Whites', servingSize: 100, servingUnit: 'g', protein: 11, category: 'Proteins' },
  { name: 'Eggs (whole)', servingSize: 1, servingUnit: 'large', protein: 6, category: 'Proteins' },
  { name: 'Greek Yogurt (plain, nonfat)', servingSize: 170, servingUnit: 'g', protein: 17, category: 'Proteins' },
  { name: 'Greek Yogurt (plain, whole)', servingSize: 170, servingUnit: 'g', protein: 15, category: 'Proteins' },
  { name: 'Ground Beef (80% lean)', servingSize: 100, servingUnit: 'g', protein: 17.2, category: 'Proteins' },
  { name: 'Ground Beef (85% lean)', servingSize: 100, servingUnit: 'g', protein: 21, category: 'Proteins' },
  { name: 'Ground Beef (93% lean)', servingSize: 100, servingUnit: 'g', protein: 21, category: 'Proteins' },
  { name: 'Ground Turkey', servingSize: 100, servingUnit: 'g', protein: 20, category: 'Proteins' },
  { name: 'Pork Chop', servingSize: 100, servingUnit: 'g', protein: 25, category: 'Proteins' },
  { name: 'Pork Tenderloin', servingSize: 100, servingUnit: 'g', protein: 26, category: 'Proteins' },
  { name: 'Salmon (Atlantic)', servingSize: 100, servingUnit: 'g', protein: 20, category: 'Proteins' },
  { name: 'Shrimp', servingSize: 100, servingUnit: 'g', protein: 20, category: 'Proteins' },
  { name: 'Tempeh', servingSize: 100, servingUnit: 'g', protein: 20, category: 'Proteins' },
  { name: 'Tilapia', servingSize: 100, servingUnit: 'g', protein: 20, category: 'Proteins' },
  { name: 'Tofu (firm)', servingSize: 100, servingUnit: 'g', protein: 17, category: 'Proteins' },
  { name: 'Tofu (silken)', servingSize: 100, servingUnit: 'g', protein: 5, category: 'Proteins' },
  { name: 'Tuna (canned in water)', servingSize: 100, servingUnit: 'g', protein: 26, category: 'Proteins' },
  { name: 'Tuna Steak', servingSize: 100, servingUnit: 'g', protein: 29, category: 'Proteins' },
  { name: 'Turkey Breast', servingSize: 100, servingUnit: 'g', protein: 30, category: 'Proteins' },
  { name: 'Whey Protein Powder', servingSize: 30, servingUnit: 'g', protein: 24, category: 'Proteins' },
  { name: 'Dark Chocolate (70%)', servingSize: 28, servingUnit: 'g', protein: 2, category: 'Snacks & Sweets' },
  { name: 'Granola Bar', servingSize: 1, servingUnit: 'bar', protein: 2, category: 'Snacks & Sweets' },
  { name: 'Ice Cream (vanilla)', servingSize: 66, servingUnit: 'g', protein: 2.3, category: 'Snacks & Sweets' },
  { name: 'Milk Chocolate', servingSize: 28, servingUnit: 'g', protein: 2, category: 'Snacks & Sweets' },
  { name: 'Popcorn (air-popped)', servingSize: 28, servingUnit: 'g', protein: 3, category: 'Snacks & Sweets' },
  { name: 'Potato Chips', servingSize: 28, servingUnit: 'g', protein: 2, category: 'Snacks & Sweets' },
  { name: 'Pretzels', servingSize: 28, servingUnit: 'g', protein: 3, category: 'Snacks & Sweets' },
  { name: 'Protein Bar (average)', servingSize: 1, servingUnit: 'bar', protein: 20, category: 'Snacks & Sweets' },
  { name: 'Tortilla Chips', servingSize: 28, servingUnit: 'g', protein: 2, category: 'Snacks & Sweets' },
  { name: 'Artichoke', servingSize: 1, servingUnit: 'medium', protein: 4.2, category: 'Vegetables' },
  { name: 'Asparagus', servingSize: 100, servingUnit: 'g', protein: 2.2, category: 'Vegetables' },
  { name: 'Broccoli', servingSize: 100, servingUnit: 'g', protein: 2.8, category: 'Vegetables' },
  { name: 'Brussels Sprouts', servingSize: 100, servingUnit: 'g', protein: 3.4, category: 'Vegetables' },
  { name: 'Cauliflower', servingSize: 100, servingUnit: 'g', protein: 2, category: 'Vegetables' },
  { name: 'Edamame', servingSize: 100, servingUnit: 'g', protein: 11, category: 'Vegetables' },
  { name: 'Kale', servingSize: 100, servingUnit: 'g', protein: 4.3, category: 'Vegetables' },
  { name: 'Mushrooms', servingSize: 100, servingUnit: 'g', protein: 3.1, category: 'Vegetables' },
  { name: 'Peas', servingSize: 100, servingUnit: 'g', protein: 5.4, category: 'Vegetables' },
  { name: 'Spinach', servingSize: 100, servingUnit: 'g', protein: 2.9, category: 'Vegetables' },
];
